/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs/promises");
const app = express();

app.use(bodyParser.json());

let todosArray = [];
let nextID = 0;
const fileName = "todos.json";

const initApp = async function () {
	try {
		const data = await fs.readFile(fileName, { encoding: "utf-8" });
		todosArray = JSON.parse(data);
		nextID = Math.max(...todosArray.map((obj) => Number(obj.id)));

		console.log(`Data of ${todosArray.length} Todos restored from file.`);
		console.log(`Last ID : ${nextID}`);
	} catch (err) {
		console.log(`ERROR : ${err.message}`);
	}
};

const updateFile = async function () {
	try {
		await fs.writeFile(fileName, JSON.stringify(todosArray), "utf-8");
	} catch (err) {
		console.log(`ERROR : ${err.message}`);
	}
};

const getIndexForId = function (id, res) {
	const num = Number(id);
	if (num === NaN) res.status(404).send(`${id} is not a number`);

	const index = todosArray.map((obj) => Number(obj.id)).indexOf(num);

	if (index === -1)
		res.status(404).send(`Todo with ID=${id} does not exist!`);
	return index;
};

const getAllTodos = function (req, res) {
	console.log("\nRoute Get All Hit!");
	res.json(todosArray);
};

const getTodo = function (req, res) {
	const id = req.params.id;
	console.log(`\nRoute Get Todo ${id} Hit!`);

	const index = getIndexForId(id, res);
	res.send(todosArray[index]);
};

const postTodo = function (req, res) {
	console.log("\nRoute Post Hit!");
	const todo = {
		id: ++nextID,
		title: req.body.title ?? "",
		description: req.body.description ?? "",
		completed: req.body.completed ?? false,
	};
	todosArray.push(todo);
	updateFile().then(res.status(201).json(`{id:${nextID}}`));
};

const updateTodo = function (req, res) {
	const id = req.params.id;
	console.log(`\nRoute Put Todo ${id} Hit!`);

	const index = getIndexForId(id, res);

	if (req.body.title) todosArray[index].title = req.body.title;
	if (req.body.description)
		todosArray[index].description = req.body.description;
	if (req.body.completed !== undefined)
		todosArray[index].completed = req.body.completed;

	updateFile().then(res.status(200).send());
};

const deleteTodo = function (req, res) {
	const id = req.params.id;
	console.log(`\nRoute Delete Todo ${id} Hit!`);

	const index = getIndexForId(id, res);
	todosArray.splice(index, 1);
	updateFile().then(res.status(200).send());
};

const startApp = function () {
	app.get("/todos", getAllTodos);
	app.get("/todos/:id", getTodo);
	app.post("/todos", postTodo);
	app.put("/todos/:id", updateTodo);
	app.delete("/todos/:id", deleteTodo);
	app.listen(3000);
};

initApp().then(startApp());

module.exports = app;
